config/routes.rb
Rails.application.routes.draw do

  root 'superheros#index'
  resources :superheros

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/superhero.rb
class Superhero < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  def index
    @superhero = Superhero.order("RANDOM()").first
  end
  
  def new
    @superhero = Superhero.new
  end

  def create
    Superhero.create(superhero_params)
    redirect_to root_path
  end

  private

  def superhero_params
    params.require(:superhero).permit(:name, :superpower)
  end

end

app/controllers/zombie_controller.rb
class ZombieController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/helpers/zombie_helper.rb
module ZombieHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/superheros/index.html.erb
<h1>Superheros</h1>
<h2><%= @superhero.name %></h1>
<h3><%= @superhero.superpower %></h2>
<br />
Refresh the page to see different heroes and powers!
<br />
<br />
<%= link_to 'Contribute', new_superhero_path %>

app/views/superheros/new.html.erb
<h1>Superhero Data</h1>
<%= simple_form_for @superhero do |f| %>
  <%= f.input :name %>
  <%= f.input :superpower %>
  <br />
  <%= f.submit 'Create' %>
<% end %>

app/views/zombie/index.html.erb
<center>

  <h1>My Homepage</h1>

<br />

<h5>This is my quiz</h5>


<br />
<br />
<%= link_to 'Contribute', new_superhero_path %>
<h1>Superhero Data</h1>
<h1><%= @superhero.inspect %></h1>
<br />


</center>

app/views/zombie/new.html.erb
<h1>Superhero Data</h1>
<%= simple_form_for @superhero do |f| %>
  <%= f.input :superhero %>
  <%= f.input :superpower %>
  <br />
  <%= f.submit 'Create' %>
<% end %>